# Generated by Django 3.2.16 on 2022-10-15 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artikel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(blank=True, max_length=255, null=True)),
                ('isi', models.TextField(blank=True, null=True)),
                ('penulis', models.CharField(blank=True, max_length=255, null=True)),
                ('publish', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(blank=True, editable=False, null=True)),
            ],
        ),
    ]
