# Generated by Django 3.2.16 on 2022-10-15 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artikel', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artikel',
            old_name='penulis',
            new_name='kategori',
        ),
    ]
